version: "3.1"
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    image: jude-backend
    secrets:
      - panoptes_username
      - panoptes_password
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    image: jude-frontend
    depends_on: 
      - backend
    volumes:
      - ./frontend/:/app
    ports:
      - "443:443"

secrets:
  panoptes_username:
    file: ./panoptes_username
  panoptes_password:
    file: ./panoptes_password
