# This Dockerfile builds the API only.

FROM python:3.9
WORKDIR /app

COPY backend/requirements.txt backend/app.py backend/download_subject_data.py backend/.flaskenv backend_start.sh ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production


EXPOSE 5000
CMD ["./backend_start.sh"]
