services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: jude-backend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: jude-frontend
    volumes:
      - ./frontend/:/app
    ports:
      - "3000:80"
