FROM python:3.9
WORKDIR /app

COPY requirements.txt ./
RUN pip install -r ./requirements.txt
COPY backend/PJimgs/ ./
COPY backend/app.py backend/download_subject_data.py backend_start.sh ./
ENV FLASK_ENV production

EXPOSE 5000
CMD ["./backend_start.sh"]
