# Build step #1: build the React front end
FROM node:16-alpine as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV NODE_ENV dev
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install
ADD ./frontend/src ./src
ADD ./frontend/public ./public
RUN npm run build

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY frontend/nginx.dev.conf /etc/nginx/conf.d/default.conf
